<?php
/**
 * @file
 * Copyright Block module.
 */

/**
 * Implements hook_block_info().
 */
function copyright_block_block_info() {
  $blocks['copyright'] = array(
    'info' => t('Copyright Notice'),
    'description' => t('Dynamic copyright years display'),
    'cache' => BACKDROP_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function copyright_block_block_view($delta = '') {
  $block = array();
  
  if ($delta == 'copyright') {
    // Load config values
    $config = config('copyright_block.settings');
    $current_year = date('Y');
    $start_year = $config->get('start_year');
    $show_range = $config->get('show_range');
    $site_name = config_get('system.core', 'site_name');
    
    // Build copyright text based on settings
    if ($show_range && !empty($start_year) && $current_year > $start_year) {
      $years = "$start_year-$current_year";
    } else {
      $years = $current_year;
    }
    
    $block['subject'] = '';
    $block['content'] = array(
      '#markup' => '<div class="copyright-block">&copy; ' . $years . ' ' . $site_name . '</div>',
    );
  }
  
  return $block;
}

/**
 * Implements hook_menu().
 */
function copyright_block_menu() {
  $items['admin/config/system/copyright-block'] = array(
    'title' => 'Copyright Block Settings',
    'description' => 'Configure copyright notice settings.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('copyright_block_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Settings form for copyright.
 */
function copyright_block_settings_form($form, &$form_state) {
  // Load config values
  $config = config('copyright_block.settings');
  $show_range = $config->get('show_range');
  $start_year = $config->get('start_year');
  
  $form['show_range'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show year range'),
    '#default_value' => isset($show_range) ? $show_range : TRUE,
    '#description' => t('Show as "2020-2025". Uncheck to show only current year "2025".'),
  );
  
  $form['start_year'] = array(
    '#type' => 'textfield',
    '#title' => t('Start Year'),
    '#default_value' => isset($start_year) ? $start_year : '',
    '#description' => t('The first year your site was active. Leave empty to use only current year.'),
    '#size' => 4,
    '#maxlength' => 4,
    '#states' => array(
      'visible' => array(
        ':input[name="show_range"]' => array('checked' => TRUE),
      ),
    ),
  );
  
  $form['actions']['#type'] = 'actions';
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save configuration'),
  );
  
  return $form;
}

/**
 * Form submit handler.
 */
function copyright_block_settings_form_submit($form, &$form_state) {
  $config = config('copyright_block.settings');
  $config->set('show_range', $form_state['values']['show_range']);
  $config->set('start_year', $form_state['values']['start_year']);
  $config->save();
  
  backdrop_set_message(t('The configuration options have been saved.'));
}